// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhertz.pns.domain;

import com.fiftyhertz.pns.domain.ClassDetails;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClassDetails_Roo_Configurable {
    
    declare @type: ClassDetails: @Configurable;
    
}
