// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhertz.pns.domain;

import com.fiftyhertz.pns.domain.MethodDetail;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MethodDetail_Roo_Configurable {
    
    declare @type: MethodDetail: @Configurable;
    
}
