// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhertz.pns.domain;

import com.fiftyhertz.pns.domain.Project;

privileged aspect Project_Roo_JavaBean {
    
    public String Project.getProjectName() {
        return this.projectName;
    }
    
    public void Project.setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
}
